"""
Give the model access to a remote container.

Check out the logs here to see the code that was executed: https://platform.openai.com/logs?api=responses

The output files are stored in the data/code_interpreter_outputs directory.
"""

from dotenv import load_dotenv
from openai import OpenAI

from scripts.openai import OPENAI_MODEL

load_dotenv()


client = OpenAI()

titanic_file = client.files.create(file=open("data/titanic.csv", "rb"), purpose="user_data")

container = client.containers.create(name="test-container", memory_limit="1g", file_ids=[titanic_file.id])


response = client.responses.create(
    model=OPENAI_MODEL,
    tools=[
        {
            "type": "code_interpreter",
            "container": container.id,
        }
    ],
    tool_choice="required",
    input=[
        {
            "role": "user",
            "content": "Create a histogram of the ages of the passengers. Use the python tool to analyze the data and create the histogram. I want the resulting histogram to be presented in a png file.",
        }
    ],
)

files = client.containers.files.list(container_id=container.id)

for file in files:
    file = client.containers.files.retrieve(container_id=container.id, file_id=file.id)

    # Download PNG files generated by the assistant
    if file.source == "assistant" and file.path.endswith(".png"):
        file_content = client.containers.files.content.retrieve(container_id=container.id, file_id=file.id)
        file_content.write_to_file(f"data/code_interpreter_outputs/{file.path.split('/')[-1]}")

print(response.output_text)
